#!/usr/bin/env node
// One-time seed for the 27 staff members from "STAFF PROFILE.docx".
// For each staff member it:
//   1. creates a Supabase auth user (provisional login email + random password,
//      email auto-confirmed — service-role key required),
//   2. inserts the bluebell_staff profile row (staff_no auto-generated by trigger,
//      auth_user_id linked so the portal scope resolves even before the staff
//      replaces their provisional email),
//   3. adds Academic staff to bluebell_teacherauth (results / CBT access).
// Finally it writes "JMI STAFF LOGIN CREDENTIALS.docx" to the Downloads folder
// so the admin can hand each staff member their login.
//
// Run from the bluebellschool project root:
//   node scripts/seed_staff_from_docx.mjs --dry   → plan only, DRAFT docx, no network
//   node scripts/seed_staff_from_docx.mjs         → real seed (needs SUPABASE_SERVICE_ROLE_KEY in .env)
// Re-running is safe: staff whose profile email already exists are skipped.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  Document, Packer, Paragraph, Table, TableRow, TableCell,
  TextRun, WidthType, AlignmentType, ShadingType,
} from 'docx';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DRY = process.argv.includes('--dry');
const PORTAL_URL = 'https://staff.bluebellschool.com';

// ---------------------------------------------------------------------------
// Staff roster transcribed from STAFF PROFILE.docx (2026). Titles (MS./MRS./
// MR/MISS) were stripped from the names so portal login-by-name stays clean.
// The docx had no emails/phones — provisional login emails are generated.
// ---------------------------------------------------------------------------
const STAFF = [
  { name: 'Nakie Doris',                sex: 'F' },
  { name: 'Uchechi Ojukwu',             sex: 'F' },
  { name: 'Emaediong Ime',              sex: 'F' },
  { name: 'Happiness Archibald',        sex: 'F' },
  { name: 'John Esther',                sex: 'F' },
  { name: 'Deborah Ifeanyi',            sex: 'F' },
  { name: 'Olivia Onyemaechi',          sex: 'F' },
  { name: 'Ngadi Chinyere Roseline',    sex: 'F' },
  { name: 'Dorine Silas',               sex: 'F' },
  { name: 'Lynda Opene',                sex: 'F' },
  { name: 'Favour Amafor Nnenna',       sex: 'F' },
  { name: 'Kindness Happy Nale',        sex: 'F' },
  { name: 'Favour Adaugo Ukwuoma',      sex: 'F' },
  { name: 'Peace Augustus',             sex: 'F' },
  { name: 'Johnson Favour',             sex: 'M' },
  { name: 'Loice Chinonyerem',          sex: 'F', designation: 'Music Instructor', subjects: ['Music'] },
  { name: 'Samuel Priscilla',           sex: 'F' },
  { name: 'Trust Sorbari',              sex: 'F' },
  { name: 'Precious Benyin',            sex: 'F' },
  { name: 'Richard Chinonyerem',        sex: 'M' },
  { name: 'Joy Friday',                 sex: 'F' },
  { name: 'Golden Ogbonna',             sex: 'F' },
  { name: 'Uche Miracle',               sex: 'F' },
  { name: 'Sunday Chidinma',            sex: 'F' },
  { name: 'Israel Sunday Unah',         sex: 'M' },
  { name: 'Olaide Gift Philip',         sex: 'F' },
  { name: 'Vivian Nke-Wisdom Richard',  sex: 'F', designation: 'School Administrator' },
];
// Everyone is Academic (teachers + the school administrator runs school admin).
// Minders/assistants/security/cleaners are added later via the admin portal.
for (const s of STAFF) {
  s.designation = s.designation || 'Teacher';
  s.department = s.department || 'Academic';
  s.subjects = s.subjects || [];
}

// ---------------------------------------------------------------------------
// Helpers (same conventions as src/utils/serverAdminAuth.ts)
// ---------------------------------------------------------------------------
function loadEnv() {
  for (const file of ['.env', '.env.local']) {
    const p = path.join(ROOT, file);
    if (!fs.existsSync(p)) continue;
    for (const line of fs.readFileSync(p, 'utf8').split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Za-z0-9_]+)\s*=\s*(.*)$/);
      if (!m) continue;
      let v = m[2].trim();
      if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
      process.env[m[1]] = v; // .env.local (loaded second) wins
    }
  }
}

const PW_ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'; // unambiguous set, matches generateTempPassword()
function genPassword() {
  const bytes = new Uint8Array(8);
  globalThis.crypto.getRandomValues(bytes);
  let out = '';
  for (const b of bytes) out += PW_ALPHABET[b % PW_ALPHABET.length];
  return `Jmi-${out}`;
}

const clean = (t) => t.toLowerCase().replace(/[^a-z]/g, '');
function makeEmail(name, used) {
  const tokens = name.split(/\s+/).filter(Boolean);
  let base = `${clean(tokens[0])}.${clean(tokens[tokens.length - 1])}`;
  let email = `${base}@bluebellschool.com`;
  let n = 2;
  while (used.has(email)) {
    // widen with the middle name token first, then a numeric suffix
    const mid = tokens.length > 2 ? clean(tokens[1]) : '';
    email = mid && n === 2
      ? `${clean(tokens[0])}.${mid}.${clean(tokens[tokens.length - 1])}@bluebellschool.com`
      : `${base}${n}@bluebellschool.com`;
    n++;
  }
  used.add(email);
  return email;
}

// ---------------------------------------------------------------------------
// Credentials DOCX
// ---------------------------------------------------------------------------
const headerCell = (text) => new TableCell({
  shading: { type: ShadingType.CLEAR, fill: '1e5128' },
  children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text, bold: true, color: 'FFFFFF', size: 20 })] })],
});
const bodyCell = (text, opts = {}) => new TableCell({
  children: [new Paragraph({ alignment: opts.center ? AlignmentType.CENTER : AlignmentType.LEFT, children: [new TextRun({ text: String(text ?? '—'), bold: !!opts.bold, size: 20 })] })],
});

function buildDocx(rows) {
  const tableRows = [
    new TableRow({ tableHeader: true, children: [headerCell('S/N'), headerCell('Name'), headerCell('Designation'), headerCell('Login Email'), headerCell('Password')] }),
    ...rows.map((r, i) => new TableRow({
      children: [
        bodyCell(i + 1, { center: true }),
        bodyCell(r.name),
        bodyCell(r.designation, { center: true }),
        bodyCell(r.email),
        bodyCell(r.password, { center: true, bold: true }),
      ],
    })),
  ];
  return new Document({
    sections: [{
      children: [
        new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'Bluebell International School', bold: true, size: 30 })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'Staff Portal — Login Credentials', size: 24 })] }),
        DRY && new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: '*** DRAFT — not yet created in the system ***', bold: true, color: 'C0392B', size: 22 })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 }, children: [new TextRun({ text: `Portal: ${PORTAL_URL} · Generated ${new Date().toLocaleDateString()} · ${rows.length} staff`, italics: true, size: 18, color: '666666' })] }),
        new Paragraph({ spacing: { after: 160 }, children: [new TextRun({ text: 'Each staff member signs in with the email and password below — or with their full name exactly as printed in the Name column, instead of the email. First task after signing in: open My Profile and replace the provisional email with your personal email, and set your own password.', size: 19 })] }),
        new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: tableRows }),
      ].filter(Boolean),
    }],
  });
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main() {
  loadEnv();
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!DRY && (!url || !key)) {
    console.error('\nSUPABASE_SERVICE_ROLE_KEY is missing. Add it to bluebellschool/.env\n(Project Settings → API → service_role secret), then re-run WITHOUT --dry.\nOr run with --dry now to preview the plan + DRAFT credentials docx.\n');
    process.exit(1);
  }
  const admin = DRY ? null : (await import('@supabase/supabase-js')).createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });

  const used = new Set();
  const results = [];
  let failed = 0;

  for (const s of STAFF) {
    const email = makeEmail(s.name, used);
    const password = genPassword();
    if (DRY) { results.push({ ...s, email, password }); continue; }

    const { data: existing } = await admin.from('bluebell_staff').select('id').ilike('email', email).maybeSingle();
    if (existing) {
      console.log(`SKIP   ${s.name} — profile already exists`);
      results.push({ ...s, email, password: '(already set — use "Reset password" in Staff Accounts)' });
      continue;
    }

    const { data: created, error: authErr } = await admin.auth.admin.createUser({
      email, password, email_confirm: true,
      user_metadata: { full_name: s.name, role: 'staff' },
    });
    if (authErr || !created?.user) {
      console.error(`FAIL   ${s.name} — auth user: ${authErr?.message}`);
      failed++; results.push({ ...s, email, password: 'FAILED' }); continue;
    }

    const { data: row, error: insErr } = await admin.from('bluebell_staff').insert({
      name: s.name, sex: s.sex, email,
      designation: s.designation, department: s.department, subjects: s.subjects,
      auth_user_id: created.user.id, status: 'active',
    }).select('staff_no').single();
    if (insErr) {
      try { await admin.auth.admin.deleteUser(created.user.id); } catch { /* best effort */ }
      console.error(`FAIL   ${s.name} — profile: ${insErr.message}`);
      failed++; results.push({ ...s, email, password: 'FAILED' }); continue;
    }

    // Academic staff can enter results / build CBT (mirrors StaffAccounts behavior)
    if (s.department !== 'Non-Academic') {
      try {
        const { data: ta } = await admin.from('bluebell_teacherauth').select('email').eq('email', email).maybeSingle();
        if (!ta) await admin.from('bluebell_teacherauth').insert({ email });
      } catch { /* non-fatal */ }
    }

    console.log(`OK     ${row?.staff_no || ''} ${s.name} <${email}>`);
    results.push({ ...s, email, password, staff_no: row?.staff_no });
  }

  const out = path.join(os.homedir(), 'Downloads', `JMI STAFF LOGIN CREDENTIALS${DRY ? ' DRAFT' : ''}.docx`);
  fs.writeFileSync(out, await Packer.toBuffer(buildDocx(results)));

  console.log(`\n${DRY ? 'DRY RUN — nothing was created.' : `Done. ${results.length - failed}/${STAFF.length} accounts created.`}`);
  console.log(`Credentials document written to:\n  ${out}`);
  if (failed) process.exitCode = 1;
}

main().catch((e) => { console.error('Seed failed:', e); process.exit(1); });
